# Generated by Django 3.2 on 2021-04-30 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Excercise',
            new_name='Exercise',
        ),
    ]
