# Generated by Django 3.2 on 2021-04-30 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_rename_excercise_exercise'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='excercise_number',
            new_name='exercise_number',
        ),
    ]
